"""
Copyright (C) 2026 - PsychedelicPalimpsest
Feel free to share this within the bounds of 
CC0 1.0 Universal
"""

from logging import RootLogger
from os.path import basename, dirname, exists, isdir, join, abspath, splitext
import os, sys, subprocess, tempfile, shutil
from typing import Generator
import json


PARENT = dirname(dirname(abspath(__file__)))
os.chdir(PARENT)

sys.path.append(PARENT)

from libs.jar_marker import taint_jar, generate_tiny

SCRIPTS_DIR = join(dirname(PARENT), "utils", "scripts")
print(SCRIPTS_DIR)
if not exists(SCRIPTS_DIR):
    raise RuntimeError("Refusing to run without use of official workspace")

sys.path.append(SCRIPTS_DIR)

from mcjar import get_piston_file, get_piston_json_path, MAPPINGIO, download_cached


USE_WINE = sys.platform != "wine32"

EXE_PREPEND = ["wine"] if USE_WINE else []


WINE_ENV = os.environ.copy()
WINE_ENV["WINEDEBUG"] = "err-all,fixme-all"


def get_mcp_temp(zip_file: str, replace_cfg: None | str = None, config_dir="conf"):
    with tempfile.TemporaryDirectory(delete=False) as f:
        if subprocess.call(["unzip", "-q", zip_file, "-d", f]) > 1:
            raise RuntimeError("Cannot unzip")
        if replace_cfg is not None:
            shutil.rmtree(join(f, config_dir))
            shutil.copytree(replace_cfg, join(f, config_dir))
        return f


# Only used in a1.1.2, just is behind a single retroguard file
def style_retroguard_only(mcp_zip, mc_versions: list[tuple[str, str]]):
    mcp_dir = None
    for mc_ver, out_tiny in mc_versions:
        if exists(out_tiny):
            continue

        if mcp_dir is None:
            mcp_dir = get_mcp_temp(mcp_zip)
            print(f"=========== {basename(mcp_zip)}: Style Retroguard ===========")

        print(f"[*] Running for {mc_ver}")
        os.makedirs(dirname(out_tiny), exist_ok=True)

        tainted_jar: str = tempfile.mktemp(".jar")
        tainted_mapped_jar: str = tempfile.mktemp(".jar")
        taint_jar(get_piston_file(mc_ver, "client"), tainted_jar)

        proc = subprocess.Popen(
            [
                "java",
                "-cp",
                join(mcp_dir, "tools", "retroguard.jar"),
                "RetroGuard",
                tainted_jar,
                tainted_mapped_jar,
                join(mcp_dir, "conf", "minecraft.rgs"),
            ],
            stdout=subprocess.DEVNULL,
        )
        if proc.wait() != 0:
            raise RuntimeError("Retroguard error")
        generate_tiny(tainted_mapped_jar, out_tiny)
        os.remove(tainted_jar)

        if exists("retroguard.log"):
            os.remove("retroguard.log")

        os.remove(tainted_mapped_jar)


import csv


def load_alpha_field_csv(path: str) -> dict[str, str]:
    out = {}
    with open(path, newline="") as csvfile:
        r = csv.reader(csvfile)
        next(r)
        next(r)
        next(r)
        for row in r:
            if not len(row):
                continue
            if not len(row[2]):
                continue
            if row[2] == "*":
                continue
            out[row[2]] = row[6]
    return out


def load_alpha_method_csv(path: str) -> dict[str, str]:
    out = {}
    with open(path, newline="") as csvfile:
        r = csv.reader(csvfile)

        next(r)
        next(r)
        next(r)
        next(r)

        for row in r:
            if 4 > len(row):
                continue
            if not row[1]:
                continue
            if "*" == row[1]:
                continue
            out[row[1]] = row[4]
    return out


# Note: You can use this for BOTH methods and fields
def load_beta_csv(path: str) -> dict[str, str]:
    out = {}
    with open(path, newline="") as csvfile:
        r = csv.reader(csvfile)

        next(r)

        for row in r:
            if not len(row):
                continue
            if not row[0]:
                continue

            out[row[0]] = row[1]
    return out


# Intelligently renames the fields and methods. Using many phases to avoid conflicts
# This beast was generated by AI, but I think it was worth it.
def tiny_renamer(mcp_fields, mcp_methods, tiny_file, ignore_conflicts: bool = False):
    print(f"[*] Starting conflict resolution on {tiny_file}...")

    entries = []
    # Key: (ObfName, Descriptor) -> Set of Candidate Names
    sig_candidates = {}

    # --- Phase 1: Parse and Collect Candidates ---
    with open(tiny_file, "r") as fin:
        for line in fin:
            clean_line = line.strip()
            if not clean_line:
                continue

            segs = clean_line.split("\t")
            entry = {"type": "OTHER", "segs": segs, "original": line}

            if clean_line.startswith("FIELD"):
                entry["type"] = "FIELD"
                if len(segs) >= 5:
                    if (true_name := mcp_fields.get(segs[4])) is not None:
                        segs[4] = true_name

            elif clean_line.startswith("METHOD"):
                entry["type"] = "METHOD"
                if len(segs) >= 5:
                    # Apply initial MCP rename
                    if (true_name := mcp_methods.get(segs[4])) is not None:
                        segs[4] = true_name

                    # Track for source hierarchy unification
                    obf, desc, mapped = segs[3], segs[2], segs[4]
                    sig_key = (obf, desc)
                    if sig_key not in sig_candidates:
                        sig_candidates[sig_key] = set()
                    sig_candidates[sig_key].add(mapped)

            entries.append(entry)

    # --- Phase 2: Unify Source Hierarchies (Fixes "Source name conflicts") ---
    # Ensures 'b' maps to 'onBlockRemoval' everywhere, never 'func_...'
    print("[*] Unifying source hierarchies...")
    source_winners = {}  # (Obf, Desc) -> BestName

    for sig, candidates in sig_candidates.items():
        if not candidates:
            continue
        # Prefer human names (not starting with func_)
        human_names = [n for n in candidates if not n.startswith("func_")]

        # Pick best name deterministically
        if human_names:
            winner = sorted(human_names)[0]
        else:
            winner = sorted(list(candidates))[0]
        source_winners[sig] = winner

    # --- Phase 3: Unify Target Names (Fixes "Target name conflicts") ---
    # Ensures 'readFromNBT' is not claimed by both 'a' and 'e' for the same descriptor
    print("[*] Checking for target collisions...")

    # Map (TargetName, Descriptor) -> List of [ObfName]
    target_claims = {}

    for (obf, desc), best_name in source_winners.items():
        # Skip constructors/special methods from de-duping if needed, though usually safe
        target_key = (best_name, desc)
        if target_key not in target_claims:
            target_claims[target_key] = []
        target_claims[target_key].append(obf)

    # Resolve collisions
    # Final Map: (Obf, Desc) -> FinalUniqueName
    final_sig_map = {}

    # Hardcoded known conflicts where the TargetName exists in the source JAR (unmapped)
    # causing a collision between MappedName and UnmappedName.
    # Format: (TargetName, Descriptor)
    KNOWN_JAR_CONFLICTS = {
        ("format", "(I)Ljava/lang/String;")
    }

    for (t_name, desc), obf_list in target_claims.items():
        is_jar_conflict = (t_name, desc) in KNOWN_JAR_CONFLICTS

        if len(obf_list) > 1 or is_jar_conflict:
            # Collision detected! multiple obf names want this target+desc OR jar conflict
            # Sort to ensure 'a' always wins over 'e' (stability)
            obf_list.sort()

            if is_jar_conflict:
                 print(f"[WARN] JAR Conflict on {t_name}{desc}: claimed by {obf_list}. Renaming all.")
                 start_idx = 0
            else:
                winner = obf_list[0]
                print(f"[WARN] Target Collision on {t_name}{desc}: claimed by {obf_list}")
                # Winner keeps the clean name
                final_sig_map[(winner, desc)] = t_name
                start_idx = 1

            # Losers (or all if jar conflict) get suffixed with their obf name to prevent crash
            for loser in obf_list[start_idx:]:
                new_name = f"{t_name}_{loser}"
                final_sig_map[(loser, desc)] = new_name
                print(f"       -> Renaming {loser} to {new_name}")
        else:
            final_sig_map[(obf_list[0], desc)] = t_name

    # --- Phase 4: Apply & Write ---
    final_lines = []

    # For local class deduplication (Pass 3 safety)
    lines_to_check = []

    print("[*] Applying resolved mappings...")

    for entry in entries:
        if entry["type"] == "OTHER":
            final_lines.append(entry["original"])
            continue

        segs = entry["segs"]

        if entry["type"] == "METHOD":
            obf, desc = segs[3], segs[2]

            # Apply the globally resolved name
            if (obf, desc) in final_sig_map:
                segs[4] = final_sig_map[(obf, desc)]

            # Prepare for local check
            if ignore_conflicts:
                dedup_key = f"{segs[1]}@{desc}:{segs[4]}"
                entry["dedup_key"] = dedup_key
                lines_to_check.append(entry)
            else:
                final_lines.append("\t".join(segs) + "\n")

        elif entry["type"] == "FIELD":
            if ignore_conflicts:
                dedup_key = f"{segs[1]}@{segs[4]}"
                entry["dedup_key"] = dedup_key
                lines_to_check.append(entry)
            else:
                final_lines.append("\t".join(segs) + "\n")

    # --- Phase 5: Local Class Collision Repair ---
    # This catches if we mapped two fields to the same name in the same class
    if ignore_conflicts:
        seen_keys = set()
        # Mark dupes
        for entry in lines_to_check:
            k = entry["dedup_key"]
            if k in seen_keys:
                entry["is_dupe"] = True
            else:
                seen_keys.add(k)

        for entry in lines_to_check:
            segs = entry["segs"]
            if entry.get("is_dupe"):
                # Suffix with obf name
                segs[4] = f"{segs[4]}_{segs[3]}"
            final_lines.append("\t".join(segs) + "\n")

    with open(tiny_file, "w") as fout:
        fout.writelines(final_lines)
    print("[*] Finished renaming operations")

# Used in a1.2.1_01-b1.3_01 (MCP 29a), and then for a few three digit MCP versions after.
# This format is differentiated by its dual use of retroguard and CSVs.
def style_alpha(
    mcp_zip,
    mc_versions: list[tuple[str, str]],
    ignore_conflicts: bool = False,
    replace_cfg: None | str = None,
    config_dir="conf",
):
    mcp_dir = None
    mcp_fields = {}
    mcp_methods = {}
    for mc_ver, out_tiny in mc_versions:
        if exists(out_tiny):
            continue

        if mcp_dir is None:
            mcp_dir = get_mcp_temp(
                mcp_zip, replace_cfg=replace_cfg, config_dir=config_dir
            )
            mcp_fields = load_alpha_field_csv(join(mcp_dir, "conf", "fields.csv"))
            mcp_methods = load_alpha_method_csv(join(mcp_dir, "conf", "methods.csv"))
            print(f"=========== {basename(mcp_zip)}: Style Alpha ===========")

        print(f"[*] Running for {mc_ver}")
        os.makedirs(dirname(out_tiny), exist_ok=True)

        tainted_jar: str = tempfile.mktemp(".jar")
        tainted_mapped_jar: str = tempfile.mktemp(".jar")
        taint_jar(get_piston_file(mc_ver, "client"), tainted_jar)

        proc = subprocess.Popen(
            [
                "java",
                "-cp",
                join(mcp_dir, "tools", "retroguard.jar"),
                "RetroGuard",
                tainted_jar,
                tainted_mapped_jar,
                join(mcp_dir, "conf", "minecraft.rgs"),
            ],
            stdout=subprocess.DEVNULL,
        )
        if proc.wait() != 0:
            raise RuntimeError("Retroguard error")
        generate_tiny(tainted_mapped_jar, out_tiny)

        tiny_renamer(
            mcp_fields, mcp_methods, out_tiny, ignore_conflicts=ignore_conflicts
        )

        os.remove(tainted_jar)

        if exists("retroguard.log"):
            os.remove("retroguard.log")

        os.remove(tainted_mapped_jar)
    if mcp_dir is not None:
        shutil.rmtree(mcp_dir)


def apply_patch(file_to_patch, patch_file):
    try:
        result = subprocess.run(
            ["patch", file_to_patch, "-i", patch_file],
            capture_output=True,
            text=True,
            check=True,
        )
        print("Patch applied successfully:")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Failed to apply patch: {e.stderr}")


# Used in b1.4_01 (MCP 30) onwards (BUT NOT ALL FORGE VERSIONS)
# This, and future versions require python injection.
# However, is still requires the jar to be renamed using the CSVs.
#
# Note: The CSV format is different to alpha
def style_python_with_renamer(
    mcp_zip,
    mc_versions: list[tuple[str, str]],
    script,
    field_loader=load_beta_csv,
    method_loader=load_beta_csv,
    patches: None | list[tuple[str, str]] = None,
    use_piston_json=False,
    replace_cfg: None | str = None,
    config_dir="conf",
):
    patches = patches if patches is not None else []

    mcp_dir = None
    mcp_fields = {}
    mcp_methods = {}
    for mc_ver, out_tiny in mc_versions:
        if exists(out_tiny):
            continue

        if mcp_dir is None:
            mcp_dir = get_mcp_temp(
                mcp_zip, replace_cfg=replace_cfg, config_dir=config_dir
            )
            mcp_fields = field_loader(join(mcp_dir, "conf", "fields.csv"))
            mcp_methods = method_loader(join(mcp_dir, "conf", "methods.csv"))

            for patch_file, file_to_patch in patches:
                print(join(mcp_dir, file_to_patch))
                apply_patch(join(mcp_dir, file_to_patch), patch_file)

            print(
                f"=========== {basename(mcp_zip)}: Style MCP with renamer ==========="
            )
        print(f"[*] Running for {mc_ver}")
        os.makedirs(dirname(out_tiny), exist_ok=True)

        tainted_jar: str = tempfile.mktemp(".jar")
        taint_jar(get_piston_file(mc_ver, "client"), tainted_jar)

        print(f"[*] Running python script inside mcp")
        subprocess.check_call(
            EXE_PREPEND
            + [
                join(mcp_dir, "runtime", "bin", "python", "python_mcp.exe"),
                abspath(join("libs", script)),
                tainted_jar,
            ]
            + ([] if not use_piston_json else [get_piston_json_path(mc_ver)]),
            cwd=mcp_dir,
            env=WINE_ENV,
        )
        tainted_mapped_jar = join(mcp_dir, "temp", "out.jar")

        generate_tiny(tainted_mapped_jar, out_tiny)

        # At this point, colistions are just normal
        tiny_renamer(mcp_fields, mcp_methods, out_tiny)
    if mcp_dir is not None:
        shutil.rmtree(mcp_dir)


EXTRACTED_FORGE_DIR = "extracted_forge_configs"


SPECIAL_SOURCE_URL = "https://repo1.maven.org/maven2/net/md-5/SpecialSource/1.11.5/SpecialSource-1.11.5-shaded.jar"
SPECIAL_SOURCE = download_cached(SPECIAL_SOURCE_URL, "SpecialSource.jar")
FORGE_MAPPINGS = join("newer_mappings", "versions")


def special_source_map(jar, mapping):
    temp = tempfile.mktemp(".jar")
    subprocess.check_call(
        ["java", "-jar", SPECIAL_SOURCE, "-i", jar, "-o", temp, "-m", mapping]
    )

    return temp


def convert_srg_config(mc_ver, diR, tiny):
    tiny_dir = join("tiny_v1s", mc_ver)
    os.makedirs(tiny_dir, exist_ok=True)

    if exists(tiny):
        return

    print(f"=========== {mc_ver}: Style MCP Config with renamer ===========")
    tainted_jar = tempfile.mktemp(".jar")
    taint_jar(get_piston_file(mc_ver, "client"), tainted_jar)

    mapping_file = "joined.srg"

    print("[*] Running SpecialSource remapper")
    tainted_mapped_jar = special_source_map(tainted_jar, join(diR, mapping_file))
    os.remove(tainted_jar)

    generate_tiny(tainted_mapped_jar, tiny)
    tiny_renamer(
        load_beta_csv(join(diR, "fields.csv")),
        load_beta_csv(join(diR, "methods.csv")),
        tiny,
    )

    os.remove(tainted_mapped_jar)


# Works with mcp and mcp-tsrg types
def forge_mcp_style(mc_ver, diR, mapping_json):
    tiny_dir = join("tiny_v1s", mc_ver)
    os.makedirs(tiny_dir, exist_ok=True)
    tiny = join(tiny_dir, mc_ver + "-mcpFORGE.tiny")

    if exists(tiny):
        return

    print(f"=========== {mc_ver}: Style Forge MCP with renamer ===========")
    tainted_jar = tempfile.mktemp(".jar")
    taint_jar(get_piston_file(mc_ver, "client"), tainted_jar)

    mapping_file = (
        mapping_json["files"]["srg"]
        if mapping_json["type"] == "mcp"
        else mapping_json["files"]["tsrg"]
    )

    print("[*] Running SpecialSource remapper")
    tainted_mapped_jar = special_source_map(tainted_jar, join(diR, mapping_file))
    os.remove(tainted_jar)

    generate_tiny(tainted_mapped_jar, tiny)
    tiny_renamer(
        load_beta_csv(join(diR, "fields.csv")),
        load_beta_csv(join(diR, "methods.csv")),
        tiny,
    )

    os.remove(tainted_mapped_jar)


def convert_from_modern_forge():
    for diR in os.listdir(FORGE_MAPPINGS):
        mc_ver = diR
        diR = join(FORGE_MAPPINGS, diR)
        assert isdir(diR)
        with open(join(diR, "mapping.json"), "r") as f:
            mapping_json = json.load(f)
        typE = mapping_json["type"]

        if typE == "mcp-tsrg" and "csv" in mapping_json["files"]:
            if mc_ver == "1.16.5":
                # TODO: This version is invalid
                continue

            forge_mcp_style(mc_ver, diR, mapping_json)
        elif typE == "mcp":
            forge_mcp_style(mc_ver, diR, mapping_json)
        elif typE != "mcp-tsrg":
            print(f"UNKNOWN TYPE: {typE}")


if __name__ == "__main__":

    tinyname = lambda mc_ver, mcp_ver: join(
        "tiny_v1s",
        mc_ver,
        f"{mc_ver}-{mcp_ver}.tiny",
    )

    stdname = lambda zip, versions, *args: (
        join("complete_packs", zip),
        [
            (
                version,
                join(
                    "tiny_v1s",
                    dirname(zip),
                    f"{version}-{splitext(basename(zip))[0]}.tiny",
                ),
                *args,
            )
            for version in versions
        ],
    )
    style_retroguard_only(*stdname("a1.1.2/revengpack16.zip", ["a1.1.2"]))

    for zip, versions, *args in [
        ("a1.2.1_01/mcp20.zip", ["a1.2.1_01"]),
        ("a1.2.1_01/mcp20a.zip", ["a1.2.1_01"]),
        # Note: the a versions are debug releases
        ("a1.2.2/mcp21.zip", ["a1.2.2a", "a1.2.2b"], True),
        ("a1.2.2/mcp22.zip", ["a1.2.2a", "a1.2.2b"], True),
        ("a1.2.2/mcp22a.zip", ["a1.2.2a", "a1.2.2b"], True),
        ("a1.2.3_04/mcp23.zip", ["a1.2.3_02"]),
        ("a1.2.5/mcp24.zip", ["a1.2.5"]),
        ("a1.2.6/mcp25.zip", ["a1.2.6"]),
        # Beta versions that use the alpha format
        ("b1.1_02/mcp26.zip", ["b1.1_02"], True),
        ("b1.2_01/mcp27.zip", ["b1.2_01"]),
        ("b1.2_01/mcp28.zip", ["b1.2_01"]),
        ("b1.3_01/mcp29.zip", ["b1.3_01"]),
        ("b1.3_01/mcp29a.zip", ["b1.3_01"]),
        ("b1.4/mcp210.zip", ["b1.4"]),
        ("b1.4_01/mcp211.zip", ["b1.4_01"]),
        ("b1.5._01/mcp212.zip", ["b1.5_01"]),
    ]:
        style_alpha(*stdname(zip, versions), *args)
    for zip, versions in [
        ("b1.4_01/mcp30.zip", ["b1.4_01"]),
        ("b1.5._01/mcp31.zip", ["b1.5_01"]),
        ("b1.6.4/mcp32.zip", ["b1.6.4"]),
        ("b1.6.5/mcp33.zip", ["b1.6.5"]),
        ("b1.6.6/mcp34.zip", ["b1.6.6"]),
    ]:
        style_python_with_renamer(*stdname(zip, versions), "mcp_midbeta_remap.py")

    for zip, versions in [
        ("b1.6.6/mcp40.zip", ["b1.6.6"]),
        ("b1.6.6/mcp41.zip", ["b1.6.6"]),
        ("b1.7.2/mcp42.zip", ["b1.7.2"]),
        ("b1.7.3/mcp43.zip", ["b1.7.3"]),
        ("b1.8.1/mcp44.zip", ["b1.8.1"]),
        ("b1.9pre-5/mcp45pre.zip", ["@omni@b1.9-pre5"]),
        ("1.0.0/mcp50.zip", ["1.0.0"]),
        ("1.1.0/mcp56.zip", ["1.1"]),
    ]:
        style_python_with_renamer(
            *stdname(zip, versions), "mcp_early_exceptor_remap.py"
        )
    for zip, versions in [
        ("1.2.3/mcp60.zip", ["1.2.3"]),
        ("1.2.4/mcp61.zip", ["1.2.4"]),
        ("12w26a/mcp615.zip", ["@omni@12w26a"]),
        ("1.2.5/mcp62.zip", ["1.2.5"]),
        ("12w17a/mcp65.zip", ["@omni@12w17a-1424"]),
        ("12w26a/mcp615.zip", ["@omni@12w26a"]),
        ("1.3.1/mcp70.zip", ["1.3.1"]),
        ("1.3.1/mcp70a.zip", ["1.3.1"]),
        ("1.3.2/mcp72.zip", ["1.3.2"]),
        ("1.4.2/mcp719.zip", ["1.4.2"]),
        ("1.4.4/mcp721.zip", ["1.4.4"]),
        ("1.4.5/mcp723.zip", ["1.4.5"]),
        ("1.4.6/mcp725.zip", ["1.4.6"]),
        ("1.4.7/mcp726.zip", ["1.4.7"]),
        ("1.4.7/mcp726a.zip", ["1.4.7"]),
        ("13w02b/mcp730c.zip", ["@omni@13w02b"]),
        # Fails to generate
        # ("13w05b/mcp734.zip", ["@omni@13w05b"]),
        ("13w09c/mcp739.zip", ["@omni@13w09c"]),
        ("1.5/mcp742.zip", ["1.5"]),
        ("1.5.1/mcp744.zip", ["1.5.1"]),
        ("1.5.2/mcp751.zip", ["1.5.2"]),
    ]:
        style_python_with_renamer(*stdname(zip, versions), "mcp_mid_exceptor.py")

    for zip, versions in [
        ("1.6.1/mcp802.zip", ["1.6.1"]),
        ("1.6.1/mcp803.zip", ["1.6.1"]),
        ("1.6.2/mcp804.zip", ["1.6.2"]),
        ("1.6.2/mcp805.zip", ["1.6.2"]),
        ("1.6.3/mcp809.zip", ["1.6.3"]),
        ("1.6.4/mcp811.zip", ["1.6.3"]),
        ("1.6.4/mcp811.zip", ["1.6.3"]),
        ("1.7.2/mcp903.zip", ["1.7.2"]),
        ("1.7.10/mcp908.zip", ["1.7.10"]),
        ("1.8/mcp910-pre1.zip", ["1.8"]),
        ("1.8.8/mcp918.zip", ["1.8.8"]),
        ("1.9/mcp924-beta1.zip", ["1.9"]),
        ("1.9.4/mcp928.zip", ["1.9.4"]),
        ("1.10.2/mcp931.zip", ["1.10.2"]),
        ("1.11.2/mcp937.zip", ["1.11.2"]),
        ("1.12/mcp940.zip", ["1.12"]),
    ]:
        style_python_with_renamer(
            *stdname(zip, versions),
            "mcp_later_exceptor.py",
            patches=[],
            use_piston_json=True,
        )



    convert_srg_config(
        "@omni@13w02b",
        join(EXTRACTED_FORGE_DIR, "13w02b", "mcp730"),
        tinyname("@omni@13w02b", "mcp730"),
    )
    for mc_ver, mcp_ver in [
        ("1.4", "mcp717"),
        ("1.4.1", "mcp718"),
        ("1.4.3", "mcp720"),
        ("1.4.5", "mcp722"),
        ("1.6", "mcp801"),
        ("1.7.2", "mcp901-alpha"),
        ("1.7.9", "mcp904"),
        ("1.7.10", "mcp905")]:
        convert_srg_config(
            mc_ver,
            join(EXTRACTED_FORGE_DIR, mc_ver, mcp_ver),
            tinyname(mc_ver, mcp_ver),
        )

    convert_from_modern_forge()
